//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BudgetDetail
    {
        public int BudgetDetailId { get; set; }
        public int Quantity { get; set; }
        public string Concept { get; set; }
        public int NumberOfEvents { get; set; }
        public decimal UnitCost { get; set; }
        public int Discount { get; set; }
        public decimal UnitCostDiscount { get; set; }
        public decimal NetTotal { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalPerEvent { get; set; }
        public int BudgetId { get; set; }
    
        public virtual Budget Budget { get; set; }
    }
}
