//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CleanedAction
    {
        public CleanedAction()
        {
            this.CleanedMaterials = new HashSet<CleanedMaterial>();
            this.CleanedMaterials1 = new HashSet<CleanedMaterial>();
            this.CleanedMaterials2 = new HashSet<CleanedMaterial>();
        }
    
        public int CleanedActionId { get; set; }
        public string Shift { get; set; }
        public int UserId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string Observations { get; set; }
    
        public virtual ICollection<CleanedMaterial> CleanedMaterials { get; set; }
        public virtual ICollection<CleanedMaterial> CleanedMaterials1 { get; set; }
        public virtual ICollection<CleanedMaterial> CleanedMaterials2 { get; set; }
        public virtual User User { get; set; }
    }
}
