//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClinicHistory
    {
        public ClinicHistory()
        {
            this.ClinicHistoryAttributes = new HashSet<ClinicHistoryAttribute>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int ClinicHistoryId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual ICollection<ClinicHistoryAttribute> ClinicHistoryAttributes { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
