//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dotation
    {
        public int DotationId { get; set; }
        public System.DateTime DotationDate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> SignedDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
