//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public System.DateTime StartEvent { get; set; }
        public System.DateTime EndEvent { get; set; }
        public bool IsCanceled { get; set; }
        public bool IsCompleted { get; set; }
        public bool PatientCame { get; set; }
        public int PatientId { get; set; }
        public int TreatmentId { get; set; }
        public bool IsException { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
