//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EventStatusChanges = new HashSet<EventStatusChanx>();
        }
    
        public int EventId { get; set; }
        public System.DateTime StartEvent { get; set; }
        public System.DateTime EndEvent { get; set; }
        public bool IsException { get; set; }
        public bool IsCanceled { get; set; }
        public bool IsCompleted { get; set; }
        public bool PatientSkips { get; set; }
        public int PatientId { get; set; }
        public int TreatmentId { get; set; }
        public int EventCapturerId { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public bool IsConfirmed { get; set; }
    
        public virtual User User { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Treatment Treatment { get; set; }
        public virtual ICollection<EventStatusChanx> EventStatusChanges { get; set; }
        public virtual Instrument Instrument { get; set; }
    }
}
