//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralPaid
    {
        public int GeneralPaidId { get; set; }
        public string ProviderName { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string TicketNumber { get; set; }
        public string PaidMethod { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
