//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryWork
    {
        public int LaboratoryWorkId { get; set; }
        public string WorkName { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool IsDeleted { get; set; }
        public int TechnicalId { get; set; }
        public int PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Technical Technical { get; set; }
    }
}
