//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public int MedicineId { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Batch { get; set; }
        public System.DateTime ExpiredDate { get; set; }
        public string Notes { get; set; }
        public bool WasReplaced { get; set; }
        public bool IsDeleted { get; set; }
        public int DataCapturerId { get; set; }
    
        public virtual User User { get; set; }
    }
}
