//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutgoingInvoice
    {
        public int InvoiceId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public System.DateTime PaidDate { get; set; }
        public string Folio { get; set; }
        public string PaidMethod { get; set; }
        public decimal TotalAmount { get; set; }
        public bool IsDeleted { get; set; }
        public int PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
