//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string Type { get; set; }
        public Nullable<int> BankId { get; set; }
        public string VoucherCheckNumber { get; set; }
        public string Observation { get; set; }
        public int FolioNumber { get; set; }
        public Nullable<int> StatementId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual PaymentFolio PaymentFolio { get; set; }
        public virtual Statement Statement { get; set; }
    }
}
