//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentFolio
    {
        public PaymentFolio()
        {
            this.Payments = new HashSet<Payment>();
            this.TreatmentPayments = new HashSet<TreatmentPayment>();
        }
    
        public int FolioNumber { get; set; }
        public System.DateTime FolioDate { get; set; }
        public int UserId { get; set; }
        public int PatientId { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<TreatmentPayment> TreatmentPayments { get; set; }
    }
}
