//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public Payment()
        {
            this.Statements = new HashSet<Statement>();
            this.PaymentFolios = new HashSet<PaymentFolio>();
        }
    
        public int PaymentId { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string Type { get; set; }
        public Nullable<int> BankId { get; set; }
        public string VoucherCheckNumber { get; set; }
        public string Observation { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual ICollection<Statement> Statements { get; set; }
        public virtual ICollection<PaymentFolio> PaymentFolios { get; set; }
    }
}
