//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public Reminder()
        {
            this.Statements = new HashSet<Statement>();
        }
    
        public int ReminderId { get; set; }
        public string Message { get; set; }
        public System.DateTime AppearDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool RequireAdmin { get; set; }
        public bool Seen { get; set; }
        public Nullable<int> SeenBy { get; set; }
        public bool AutoGenerated { get; set; }
        public Nullable<System.DateTime> SeenDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Statement> Statements { get; set; }
    }
}
