//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentPayment
    {
        public int TreatmentPaymentId { get; set; }
        public int TreatmentPriceId { get; set; }
        public System.DateTime TreatmentDate { get; set; }
        public decimal Price { get; set; }
        public int Discount { get; set; }
        public int Quantity { get; set; }
        public decimal Total { get; set; }
        public int FolioNumber { get; set; }
        public Nullable<int> StatementId { get; set; }
    
        public virtual PaymentFolio PaymentFolio { get; set; }
        public virtual Statement Statement { get; set; }
        public virtual TreatmentPrice TreatmentPrice { get; set; }
    }
}
